Add environment choice to Jenkinsfile
ONSdigital/business-index-elastic-index pull request #4
Opened 2018-08-02 14:41 UTC by ONS-Tom

- Add choice of environment as build parameter (dev/test/beta)
- Add automatic creation of index name, e.g. `bi-dev-02082018`

2018-08-03 08:22 UTC, willis7 requested changes

2018-08-03 08:22 UTC, willis7 commented on Jenkinsfile
> +                    INDEX_NAME = "bi-${ENVIRONMENT}-${currentDate}"
`INDEX_NAME ` would suggest this is an environment variable, but it's a standard Groovy variable. It should be written following that convention

2018-08-03 08:22 UTC, willis7 commented on Jenkinsfile
> +                    sh "business-index-api/conf/scripts/index_exists.sh $ELASTIC_HOST $ELASTIC_PORT $INDEX_NAME"
the `sh` step doesnt belong in a script block. If you're doing this because of the scope of current date, then you may be better off with something like:
```
environment{
INDEX_NAME = "bi-${ENVIRONMENT}-${new Date().format('ddMMyyyy')}"
}
```

2018-08-03 08:22 UTC, willis7 commented on Jenkinsfile
> +                    INDEX_NAME = "bi-${ENVIRONMENT}-${currentDate}"
exactly as you have done with `currentDate`

2018-08-03 08:40 UTC, ONS-Tom commented on Jenkinsfile
> +                    sh "business-index-api/conf/scripts/index_exists.sh $ELASTIC_HOST $ELASTIC_PORT $INDEX_NAME"
Would this be in the `environment { ... }` for the specific stage or at the top of the `Jenkinsfile`?

2018-08-22 07:24 UTC, willis7 approved these changes

2018-08-22 07:30 UTC, merged